### ISSUE TITLE
Annotation coordinates

### ISSUE THREAD

**Issue by gc625** [tudelft-iv/view-of-delft-dataset#10]
Hi, thanks for the great dataset and tools. I was wondering what coordinate system is the label/annotations in w.r.t? i.e. what transformations will I have to apply to the radar points such that the annotations and the points are in the same coordinate system? I couldn't seem to find this detail in the jupyter notebooks. Apologies if I missed it.

**Comment by BalazsSzekeres** [comment]
Hi!

As per the Kitti format, the labels are in the camera frame by default.

For 3D visualisation when you create an instance of the `Visualization3D` class, you can define your frame of reference using the `origin` argument, eg:
```
from vod.visualization import Visualization3D
vis_3d = Visualization3D(frame_data=frame_data, origin='radar')
```
Then to visualise both radar points and the annotations you can use:
```
vis_3d.draw_plot(radar_origin_plot=True,
radar_points_plot=True,
radar_velocity_plot=True,
annotations_plot=True)
```

For manually transforming the labels you can take a look at: https://github.com/tudelft-iv/view-of-delft-dataset/blob/61937cf63edc5dbc61df6edac1db7b534656feee/vod/visualization/helpers.py#L69

Let me know if this answers your question!
