### ISSUE TITLE
transformation problem regarding radar points accumulation

### ISSUE THREAD

**Issue by RealYuWang** [tudelft-iv/view-of-delft-dataset#102]
Hi there,

I'm trying to **manually overlay 3 frames of radar data**, and according to your description you do it by **“transforming point clouds from previous scans to the coordinate system of the last scan.”** I would like to know how you actually did this? Because there is no direct frame-to-frame radar transformation matrix in the dataset.

**My compromise idea is(given 2 consecutive frames of radar data, e.g. 00000.bin and 00001.bin):**
1. using `t_camera_radar` to transfrom both original point clouds into camera coordinates
2. using `t_map_camera`(read from given pose file) to transfrom camera coordinates point clouds into gloabl coordinates
3. fuse these two point clouds by simply stacking them vertically
4. finally, using `t_camera_map` and `t_radar_camera`(both from 2nd frame's transformations) to transform fused point clouds into 2nd frame's radar coordinate system

Now the problem is, in the 2nd step, when transforming camera coordinate point cloud into world coordinate using given pose file, the transformed point clouds are far away form each other(see picture, both radar and lidar are now in world coordinate), which is not what I expected, e.g. pretty close to each other. Is there something wrong with the pose file or my understanding of it is wrong?

![Screenshot from 2024-10-18 11-24-55](https://github.com/user-attachments/assets/6badcf46-ace2-4519-b2e6-8a8ac6c85f48)

`frame_data = FrameDataLoader(kitti_locations=kitti_locations, frame_number="00000")
frame_data_2 = FrameDataLoader(kitti_locations=kitti_locations, frame_number="00001")
transforms = FrameTransformMatrix(frame_data)
transforms_2 = FrameTransformMatrix(frame_data_2)

radar_points_camera_frame = transform_pcl(frame_data.radar_data, transforms.t_camera_radar)
radar_points_camera_frame_2 = transform_pcl(frame_data_2.radar_data, transforms_2.t_camera_radar)
lidar_points_camera_frame = transform_pcl(frame_data.lidar_data, transforms.t_camera_lidar)
lidar_points_camera_frame_2 = transform_pcl(frame_data_2.lidar_data, transforms_2.t_camera_lidar)

radar_points_world_frame = transform_pcl(radar_points_camera_frame, transforms.t_map_camera)
radar_points_world_frame_2 = transform_pcl(radar_points_camera_frame_2, transforms_2.t_map_camera)
lidar_points_world_frame = transform_pcl(lidar_points_camera_frame, transforms.t_map_camera)
lidar_points_world_frame_2 = transform_pcl(lidar_points_camera_frame_2, transforms_2.t_map_camera)`

**Comment by andraspalffy** [comment]
It could be that the localization stack of the very first positions of certain scenes where not converged yet, and thus you can see large jumps between frames. This is not an error of the devkit or the transformation, but rather the data itself. 
Please try to plot the position itself first for a couple of frames to double check this, using last block of this notebook:

https://github.com/tudelft-iv/view-of-delft-dataset/blob/main/2_frame_transformations.ipynb

With that, you can eliminate the TF errors.
