### ISSUE TITLE
no alignment in 2D visualization.

### ISSUE THREAD

**Issue by OuyangJunyuan** [tudelft-iv/view-of-delft-dataset#12]
I found that some 3D BBoxes at the edges of the images did not match their corresponding objects, as follows:
![image](https://user-images.githubusercontent.com/37474760/176890668-2ac20ad9-9165-4f2d-a642-1eb9ef5d5760.png)
However, it should do not like this because the images stored in image_2 have been rectified.
![image](https://user-images.githubusercontent.com/37474760/176890945-186bb85a-45a7-48fa-aaa7-fd53b3fc854a.png).
did I misunderstand these?

**Comment by TarunKumar1995-glitch** [comment]
2D visualisation is only to understand the context of the scene. We recommend that 3D visualisation tools are used for qualitative analysis. Also, the synchronisation between the three sensors/labels is very good but not "perfect". So, any offset thereby will be more prominent at the edges, more so towards the field-of-view boundary.
