### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by hjfenghj** [tudelft-iv/view-of-delft-dataset#13]
Hello, I sent a data set download request using the education email. Did you see the email prompt here? I would appreciate it if you could tell me how long it will take to verify my identity;
email：hjfeng@stu.xidian.edu.cn

**Comment by andraspalffy** [comment]
Thanks for using our dataset and closing the issue after you got access.

For anyone with a similar problem, we kindly ask you to:

1. be patient, we will get to your request
2. Do not submit a request multiple times, it makes our work harder
3. Please follow the instructions (e..g. no personal email addresses)
4. Please use the English language

Thank you!
Andras
