### ISSUE TITLE
pp-radar performance on validation set

### ISSUE THREAD

**Issue by gc625** [tudelft-iv/view-of-delft-dataset#17]
Hi, I was wondering if it would be possible to publish performance results for pointpillars on the validation set of the data? When and how will we be able to test our own custom models on the test set? Thank you!

**Comment by gc625** [comment]
I see, thank you. Regarding pointpillar performance on the validation set, would it be possible to release your results?

**Comment by andraspalffy** [comment]
Sorry, we do not have that easily available for the final splits. Maybe later we can release that too.

**Comment by TarunKumar1995-glitch** [comment]
The model config shared in the pp-radar [guidelines](https://github.com/tudelft-iv/view-of-delft-dataset/blob/main/PP-Radar.md) was an outdated version. It is now updated and should provide comparable results.
