### ISSUE TITLE
k3d unavailable issue

### ISSUE THREAD

**Issue by ZixianReid** [tudelft-iv/view-of-delft-dataset#2]
The 3D figure is not shown. 

run command 

 jupyter nbextension enable  --py --sys-prefix k3d

after 

jupyter nbextension install --py --sys-prefix k3d

**Comment by BalazsSzekeres** [comment]
Hi Zixian,

Thank you for raising an issue. Do you mean after applying the two commands the plots are still not displayed?

Could you additionally run `jupyter labextension install k3d`?

**Comment by ZixianReid** [comment]
Hi BalazsSzekeres,
     Thanks for the respone. I have additionally run `jupyter labextension install k3d`. And the plots are not available utile I run `jupyter nbextension enable --py --sys-prefix k3d`.

**Comment by BalazsSzekeres** [comment]
I understand, I have updated the documentation based on your comment! Thank you for your input!
