### ISSUE TITLE
The point cloud data in the dataset is the full values from radar sensor or  filtered values?

### ISSUE THREAD

**Issue by yaoshanliang** [tudelft-iv/view-of-delft-dataset#20]
As is described in the title, do you have filtered some values from the radar sensor, like removing some noisy data?

**Comment by andraspalffy** [comment]
Hello, we did not filter out any points in the published data.
That means all points, including underground, out of  field of view, very weak, very close, and very far points are all there - it is up to the user to filter them.

Note, however, that only the camera field of view is annotated, points outside that are available but usually will not fall in any boxes.
