### ISSUE TITLE
Camera Version

### ISSUE THREAD

**Issue by ZixianReid** [tudelft-iv/view-of-delft-dataset#21]
Hi,  I was wondering know the camera version details of the camera used for collecting this datasets.  And whether the camera used supports auto focus function.

**Comment by andraspalffy** [comment]
The stereo camera system is a pair of IDS 306xCP-C color camera systems.
The focus was not modified, I suspect that such cameras are always set to infinite focus.
Please refer to the camera manufacturer's documents for more details.
