### ISSUE TITLE
Occlusion setting for evaluation

### ISSUE THREAD

**Issue by MrTooOldDriver** [tudelft-iv/view-of-delft-dataset#22]
Hi. I had a question about the occlusion setting for evaluation. 

The evaluation script in this repo uses [4] for max occlusion, which means it gonna evaluate all objects that have any occlusion.
https://github.com/tudelft-iv/view-of-delft-dataset/blob/3c35494d7c13a32dc59697451d7430fc0bb4d31b/vod/evaluation/kitti_official_evaluate.py#L35

This setting is different to the original openpcdet setting [here](https://github.com/open-mmlab/OpenPCDet/blob/0642cf06d0fd84f50cc4c6c01ea28edbc72ea810/pcdet/datasets/kitti/kitti_object_eval_python/eval.py#L33) and wasn't mentioned in documents and issues.

Could you please confirm this is the correct occlusion setting for evaluation? And pp-radar, pp-lidar results on paper were evaluated with this occlusion setting?

Thank you very much in advance.

**Comment by andraspalffy** [comment]
Hi,
Good observation!
That is correct, all objects are evaluated and we used this approach in the reports.
We found it simpler this way, as we already had several metrics to report.
