### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by chyohoo** [tudelft-iv/view-of-delft-dataset#26]
Hello, thank you for your excellent dataset.
I found in your evaluation, that gt values are added by 0.01. What's the reason for that?
https://github.com/tudelft-iv/view-of-delft-dataset/blob/089c283a362d08e503724354d5821e30d480fc0c/vod/evaluation/kitti_official_evaluate.py#L414

**Comment by srimannarayanabaratam** [comment]
Thanks for raising the issue.

Indeed it is not supposed to be there. It was a remnant from debugging an old issue. It is fixed in the latest commit.

**Comment by NawelDorsafbensaleh** [comment]
avez vous un code de classification des objets en utilisant radar 4D?
