### ISSUE TITLE
Data annotation doesn't include object id

### ISSUE THREAD

**Issue by LJacksonPan** [tudelft-iv/view-of-delft-dataset#3]
Hi there,

Firstly great thanks for your dataset which has very good quality radar and LiDAR point clouds. However, we found that your data annotation doesn't include object ids, which are mainly for object tracking tasks. KITTI's tracking label format includes two extra parameters at the beginning for sequence number and tracking id, here's an example:

![image](https://user-images.githubusercontent.com/59381535/170799635-2aa8a279-4ece-4b0e-ba3c-f41af13e9679.png)

The KITTI tracking annotation format is specified as following:

![image](https://user-images.githubusercontent.com/59381535/170799158-4d27645e-b594-4227-8fa8-41e916d6a3b7.png)

However, I couldn't find any object id annotations. Will the object id annotation be released later? Many thanks in advance!

**Comment by BalazsSzekeres** [comment]
Hi!

Thank you for the question! Indeed, it is not included in the current release but is planned to be released later. I will keep this issue open, and close it when it is added, so you will get notified as well.

Hope this answers your question!

**Comment by andraspalffy** [comment]
Hi @LJacksonPan, can you contact me privately please? I do have a first version of the trackid-s and I would like to discuss how you would use it!

Thanks, Andras

**Comment by andraspalffy** [comment]
Track id-s now are available.

**Comment by 304886938** [comment]
Hello, thank you very much for providing the dataset containing 4D Radar. I'm trying to do 3D object tracking based on the dataset. I would like to ask if you can provide a tracking evaluation script. I'm looking forward to your reply!

**Comment by andraspalffy** [comment]
Hi, we do not have a tracking evaluation script, sorry.
We encourage you to make your own. You can also contact our colleague [Hidde Boekema](https://www.tudelft.nl/staff/h.j.boekema/?cHash=425cdaa1459bd5ce5fa0987ae83d8a1d) as he is working on prediction and probably can direct you a bit better.
