### ISSUE TITLE
KeyError: 'truck'   vis_3d.draw_plot(annotations_plot=True)

### ISSUE THREAD

**Issue by mendoza-G** [tudelft-iv/view-of-delft-dataset#31]
frame 00001 00002 , using API  vis_3d.draw_plot(annotations_plot=True),error occurred, but there is nothing wrong with the label.
![图片](https://user-images.githubusercontent.com/81526517/216010977-c58080e6-86a3-43b2-badf-378b01249ee6.png)
![图片](https://user-images.githubusercontent.com/81526517/216011016-74eb649e-8d03-45de-ad55-84fe16e707f7.png)
frame 00356 worked.
![图片](https://user-images.githubusercontent.com/81526517/216012229-01fc1bbd-143d-414e-9049-6a3086565056.png)

**Comment by andraspalffy** [comment]
This is a simple "KeyError", which means that there is no entry in the dictionary "class_colors" with those keys ("truck", or "motor"). The reason for this is in:

https://github.com/tudelft-iv/view-of-delft-dataset/blob/d2c856ea1f1a3f57921c0bec4f8a651d4f1ba413/vod/visualization/settings.py

Where we defined colors for a lot of classes, but not for these strings specifically. You can do several things to solve this.

1. Modify the settings.py file to add colors as you like, probably the easiest
2. Handle the exception somehow, and set a default color for "unknown" objects
3. Re-label these objects, e.g. something like "if object_class == 'truck': object_class = 'car'

Hope this helps. Andras
