### ISSUE TITLE
The model of pp-radar (5 scans) is not evaluated well

### ISSUE THREAD

**Issue by JZhong-Li** [tudelft-iv/view-of-delft-dataset#33]
I have trained the radar_5frames_pointpillars.yaml based on the , but the evaluated results are not good. The 'Truncation' in eval.py has also been commented out. Here is my results and config files.

![2023-02-16 19-33-38屏幕截图](https://user-images.githubusercontent.com/76928254/219359273-798244ac-fbed-4cba-b862-61f0f3f3712a.png)

![2023-02-16 20-00-39屏幕截图](https://user-images.githubusercontent.com/76928254/219359745-9f168093-6143-4bf1-acc7-27205850ca20.png)

![2023-02-16 20-01-20屏幕截图](https://user-images.githubusercontent.com/76928254/219359777-c715e1da-8234-49d7-9349-4dc8d06af10d.png)

![2023-02-16 20-01-59屏幕截图](https://user-images.githubusercontent.com/76928254/219359819-9df874e8-926f-4d83-b594-00af9e924d6a.png)

**Comment by JZhong-Li** [comment]
Sorry, something is missing. The backbone is RadarPillarVFE.

**Comment by andraspalffy** [comment]
Hello. Some things to notice here:
1, you use the OpenPCDet eval kit, not ours. That is ok if that is what you want, but you have to be very sure which number means what.
2, You use both VR and VR_comp. Why? Just VR is just noise if you have the compensated.
3, Maybe you forgot to normalize your data during loading.

Hope this helps! 
Andras

**Comment by shuxiusuxiu** [comment]
> Hello. Some things to notice here: 1, you use the OpenPCDet eval kit, not ours. That is ok if that is what you want, but you have to be very sure which number means what. 2, You use both VR and VR_comp. Why? Just VR is just noise if you have the compensated. 3, Maybe you forgot to normalize your data during loading.
> 
> Hope this helps! Andras

Hi! i met the same problem, the result seems not satisfactory, and you suggested to normalize data.
But i have some confusions about normalization.

1) what is the motivation of normalizing point?
2) which attributes should be normalized? (v_comp, RCS?)
3) the statictics(mean, std) used for normalization should be computed in the whole traning set(one for all the frame) or just in current frame

**Comment by andraspalffy** [comment]
> 

see #69
