### ISSUE TITLE
Question about radar，radar_3_scans and radar_5_scans.

### ISSUE THREAD

**Issue by HRN1024** [tudelft-iv/view-of-delft-dataset#36]
Hello, authors. 
Could you tell me the difference between radar，radar_3_scans, and radar_5_scans in the dataset?
Best regards.

**Comment by andraspalffy** [comment]
Hello, you can read about this here:
[https://tudelft-iv.github.io/view-of-delft-dataset/docs/SENSORS_AND_DATA.html#radar](https://tudelft-iv.github.io/view-of-delft-dataset/docs/SENSORS_AND_DATA.html#radar)

It is also described in the paper.

In short, 3 scans and 5 scans are different versions of the dataset, where each radar frame contains not just points from the current scan, but also from the 2/4 previous ones. In other words, you have accumulated data.
