### ISSUE TITLE
How can I evaluate my model in testing set?

### ISSUE THREAD

**Issue by ME-SJTU** [tudelft-iv/view-of-delft-dataset#39]
Hi, thanks for your excelent work on the 4D Radar dataset. I have trained my own model based on the training dataset, and evaluated it by val dataset. I would like to ask you how I can evaluate my model in testing set? Thanks.

**Comment by andraspalffy** [comment]
Hello Li,

the evaluation is done by us semi-manually. You can use this form. 
[https://forms.gle/71jPeVZr2LVZAHy5A](https://forms.gle/71jPeVZr2LVZAHy5A)
