### ISSUE TITLE
 ego-car's x/y axis difference between frames

### ISSUE THREAD

**Issue by shawrby** [tudelft-iv/view-of-delft-dataset#42]
Hi!

How do I know the x, y axis values that the ego-car difference between frames has moved?

**Comment by andraspalffy** [comment]
Hello,

which coordinate frame are you referring?  x y values compared to what? In what sense did they change?
Please be more specific.

Andras

**Comment by shawrby** [comment]
@andraspalffy 

Thanks for your reply.

I want to accumulate radar pointcloud for an arbitrary number of frames.
To do this, radar pointcloud must be compensated for the ego car's movement.

What should I do??
