### ISSUE TITLE
Did not get any reply after requiring the data

### ISSUE THREAD

**Issue by BaiLiping** [tudelft-iv/view-of-delft-dataset#5]
Hi, I have filed multiple requirements for access of the dataset. But I did not receive any reply.

**Comment by BalazsSzekeres** [comment]
You should have received an email by now.

To all: please be patient, eligibility is checked manually, and we have a lot of applications, thank you for the understanding!

**Comment by liuhuaijjin** [comment]
Hi, I have also submitted multiple requests for dataset access, but I have not received any response. My email is 20011080008@stu.hqu.edu.cn.
