### ISSUE TITLE
When will the activity attribute annotations for objects be published.

### ISSUE THREAD

**Issue by yanglong2000** [tudelft-iv/view-of-delft-dataset#51]
Hello Author,

I am wondering When will the activity attribute annotations for objects be published.

Thank you so much in advance!

**Comment by andraspalffy** [comment]
Hello, can you let me know what attributes you need exactly?

**Comment by yanglong2000** [comment]
Thank you for your reply.
I want to know the activity attributes of objects for these five actions ("stopped," "moving," "parked," "pushed," "sitting").

**Comment by andraspalffy** [comment]
Stopped and moving are available already, see prev. issue. Would that be a start?

**Comment by yanglong2000** [comment]
I found the answer in issue #53. Stopped and moving are already available.
Thanks.
