### ISSUE TITLE
Dataset for the task of motion object detection

### ISSUE THREAD

**Issue by lbhwyy** [tudelft-iv/view-of-delft-dataset#53]
Thank you for your excellent dataset！
 I have a question regarding Issue 8, where you explained the poor performance of PP-Lidar. In your explanation, you mentioned that you replaced truncation with other attributes, such as whether the object is moving or not. So, I would like to ask if it is possible to perform motion object detection on this dataset.

**Comment by andraspalffy** [comment]
Hello,

The original annotations (i.e. the first download link you got, original labels, not with track ids) contains that at the "trunction" field, 0 vs 1 stands for moving and static.

With that, you will be able to do moving object detection!
