### ISSUE TITLE
Angle calculation

### ISSUE THREAD

**Issue by armbruer** [tudelft-iv/view-of-delft-dataset#55]
Hi, 
I'm trying to understand how to calculate azimuth from the annotated data.

(all coordinates in camera coordinates)

```python
print(np.arctan2(label['x'], label['z']) * 180 / np.pi)
```

but this does not line up with 
```python
print(label['alpha'] * 180 / np.pi)
```

The values I get from the arctan2 angle calculation seem appropriate when drawing them on paper in a coordinate grid. However, in your documentation it clearly states that objects are only annotated within horizontal FoV: ±32°, vertical FoV: ± 22°, making me further question the validity of my azimuth values being > +-32 degrees.

Is my assumption wrong that azimuth=alpha? Or is the arctan2 angle calculation wrong?

Thanks
Eric

**Comment by andraspalffy** [comment]
Hi, please check the KITTI annotation documentation for this. Alpha is at not azimuth. 
One is at which direction you see the object, the other is at which direction does the object look to.

Example difference is at this figure from their paper.
![image](https://github.com/tudelft-iv/view-of-delft-dataset/assets/7983561/f30013af-2a28-46b5-b3d9-684cadfb684c)
