### ISSUE TITLE
How to use your assessment method, get mAP and mAOS

### ISSUE THREAD

**Issue by min-zhang** [tudelft-iv/view-of-delft-dataset#56]
How to use your assessment method, get mAP and mAOS, here is my data:
#`2023-07-05 14:16:18,853   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:25.2931, 35.8688, 30.2304
bev  AP:34.3534, 41.2079, 37.0070
3d   AP:13.5977, 17.5404, 14.6623
aos  AP:22.00, 34.01, 28.79
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:21.6496, 32.8158, 26.9882
bev  AP:31.7833, 40.4042, 33.8964
3d   AP:7.0489, 12.1813, 9.6848
aos  AP:17.99, 30.88, 25.39
Car AP@0.70, 0.50, 0.50:
bbox AP:25.2931, 35.8688, 30.2304
bev  AP:53.9248, 58.3119, 50.3598
3d   AP:34.7278, 41.2159, 36.9743
aos  AP:22.00, 34.01, 28.79
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:21.6496, 32.8158, 26.9882
bev  AP:52.7421, 57.3406, 49.3869
3d   AP:31.6778, 40.5127, 33.8923
aos  AP:17.99, 30.88, 25.39
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:28.7664, 26.7176, 22.2800
bev  AP:26.4072, 21.3220, 20.4711
3d   AP:16.2190, 13.5128, 13.1590
aos  AP:28.29, 26.09, 21.88
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:26.2926, 21.6179, 19.5190
bev  AP:22.2260, 17.9081, 16.0608
3d   AP:9.9817, 8.1055, 6.9494
aos  AP:25.61, 20.92, 18.87
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:28.7664, 26.7176, 22.2800
bev  AP:48.2595, 40.4788, 33.9854
3d   AP:38.4618, 31.6497, 30.0935
aos  AP:28.29, 26.09, 21.88
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:26.2926, 21.6179, 19.5190
bev  AP:46.2196, 37.6173, 33.2550
3d   AP:36.3881, 30.1446, 26.2724
aos  AP:25.61, 20.92, 18.87
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:60.9057, 58.7827, 52.4480
bev  AP:70.8855, 63.8257, 56.6782
3d   AP:36.7310, 31.9714, 31.0531
aos  AP:60.82, 58.68, 52.36
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:62.0980, 56.1747, 50.1514
bev  AP:71.2272, 63.1126, 56.4553
3d   AP:33.3966, 29.5327, 26.2988
aos  AP:62.00, 56.07, 50.06
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:60.9057, 58.7827, 52.4480
bev  AP:84.8932, 76.9164, 68.6398
3d   AP:81.7922, 73.7306, 66.0486
aos  AP:60.82, 58.68, 52.36
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:62.0980, 56.1747, 50.1514
bev  AP:86.0499, 78.9152, 71.5783
3d   AP:81.5084, 72.7171, 65.6249
aos  AP:62.00, 56.07, 50.06`

**Comment by andraspalffy** [comment]
See this please
https://github.com/tudelft-iv/view-of-delft-dataset/issues/8#issuecomment-1231418778
