### ISSUE TITLE
trained model in paper

### ISSUE THREAD

**Issue by shawrby** [tudelft-iv/view-of-delft-dataset#6]
Hi there.

First of all, thank you for releasing this wonderful dataset.

Could you release several trained lidar & radar models in your paper for baseline model evaluation?

**Comment by andraspalffy** [comment]
Dear shawrby, 

Thank you for your kind words and question.

For now, we will not release the models as they are almost exactly the same PointPillars as the original OpenPCDet:

[https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/kitti_models/pointpillar.yaml](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/kitti_models/pointpillar.yaml
)
More specifically, for LiDAR we did not change anything, just the detection range. 

For radar,  pillar height is adapted to our point cloud. Mind you, radar points can be below the target so our pillars are very tall. The number of points per pillar was somewhat limited MAX_POINTS_PER_VOXEL: 10 as the original 32 was never even close with radar.

We may share the models later when our official evaluation starts.
