### ISSUE TITLE
about the position and coordinate system of the ego vehicle’s odometry

### ISSUE THREAD

**Issue by Jonathans575** [tudelft-iv/view-of-delft-dataset#65]
Hi,

![image](https://github.com/tudelft-iv/view-of-delft-dataset/assets/39874362/4597dd9b-b424-42ac-9f60-f48a3208283d)

The figure above has not show the position of the ego vehicle’s odometry and its coordinate system.
Could you please add it into the figure for a better understanding?

**Comment by andraspalffy** [comment]
Hello, the car's position to the world is given as TF-s to the camera frame, e.g. UTM2Camera, to use that the camera frame is enough. What is your exact usecase that needs the odometry frame? 

Btw. it is between the two front seats, x pointing forward, y to the left if I am correct.
