### ISSUE TITLE
Relative Radar Measurement

### ISSUE THREAD

**Issue by paaraujo** [tudelft-iv/view-of-delft-dataset#66]
Hello @andraspalffy ,

The documentation says `The provided radar point clouds are ego-motion compensated for ego-motion between the capture of radar and camera data (i.e. overlaying camera and radar data should give a consistent image).`

I want to access the radar measurements without compensation. For example, radar detections in the radar coordinate system, no compensation, no transformation to maps, etc. Similar to what we do using Doppler velocity, elevation angle and azimuth angle to find the relative position of a detection.

Could you give any insight on this? Thank you!

**Comment by andraspalffy** [comment]
The dataset gives you both compensated and uncompensated velocity per point, see:
https://tudelft-iv.github.io/view-of-delft-dataset/docs/SENSORS_AND_DATA.html#radar
