### ISSUE TITLE
normalization detail when processing radar iput

### ISSUE THREAD

**Issue by shuxiusuxiu** [tudelft-iv/view-of-delft-dataset#69]
![image](https://github.com/tudelft-iv/view-of-delft-dataset/assets/49628778/e32a9266-757b-41c8-b655-c549571ee2a5)

![image](https://github.com/tudelft-iv/view-of-delft-dataset/assets/49628778/ad36bbe9-2673-4734-970b-af021fee3930)

Hi! i met the same problem, the pointpillar-radar-5scan result seems not satisfactory, and you suggested to normalize data.
But i have some confusions about normalization.

1) what is the motivation of normalizing point?
2) which attributes should be normalized? (v_comp, RCS?)
3) the statictics(mean, std) used for normalization should be computed in the whole traning set(one for all the frame) or just in current frame

_Originally posted by @shuxiusuxiu in https://github.com/tudelft-iv/view-of-delft-dataset/issues/33#issuecomment-1712409768_

**Comment by andraspalffy** [comment]
Hello, I have updated the document to make this clearer, see below:

[https://github.com/tudelft-iv/view-of-delft-dataset/blob/main/PP-Radar.md#kitti_datasetpy](https://github.com/tudelft-iv/view-of-delft-dataset/blob/main/PP-Radar.md#kitti_datasetpy)

In short:

1.  common thing done in literature, helps regularization. You are welcome to try it without it as well!
2. Everything was normed except x-y-z and time. See new commit.
3. Whole training set, one for all the frame. This Is btw a consequence of the code that you see linked, same as KITTI did. You can, however, try to do this per frame in the VFE possibly.
