### ISSUE TITLE
pose info for frame #6759

### ISSUE THREAD

**Issue by Xavier0226** [tudelft-iv/view-of-delft-dataset#7]
Hi, I met some problems when visualizing the ego-car trajectory w.r.t. the pose infomation. 
The transformation between frame #6759 and frame #6760 seems not to match the ego-motion shown in their corresponding image. The computed transform matrix shows that the ego-car has a large yaw angle change between two frames, but on the images, the ego-car is forward. 

Could the repo owner explain this or check if the pose information of this frame is converted correctly?

**Comment by andraspalffy** [comment]
@Xavier0226 thanks for your feedback.
As mentioned in #4 there can be frames where the localization stack (a complex pipeline of GPS, RTK, odometry, IMU fusion) makes a mistake, especially at the beginning of sequences. We suggest either ignoring or interpolating these poses instead.

As for this concrete frame, @BalazsSzekeres will check it specifically!
