### ISSUE TITLE
Rotation beyond range [-pi,pi]

### ISSUE THREAD

**Issue by XiangyPeng** [tudelft-iv/view-of-delft-dataset#70]
Hi, I have a question regarding the rotation in annotation. 
According to the document, it should with [-pi,pi]. But I found some labels have a rotation beyond this range.

For example, in frame 00756, the label is: 
_Pedestrian 0 2 2.171941535874267 925.7916 902.354 1077.5109 1183.4404 1.8198169204622656 0.8863006796690807 0.7429020101345508 0.30850213879168925 4.029782619287887 11.35048340265276 -4.08407081359279 1_
**where the rotation is  -4.08407081359279.**

Do you have any clue about it?
Thank you in advance.

**Comment by andraspalffy** [comment]
As discussed in email, just norm it back to the -pi to pi domain.
Thanks!
