### ISSUE TITLE
Stereo pairs

### ISSUE THREAD

**Issue by Ecalpal** [tudelft-iv/view-of-delft-dataset#73]
Because the VoD dataset emploied a stereo camera to capture RGB images, do you have any plan to release the right view (image_3) image?

**Comment by andraspalffy** [comment]
Please contact me on my tu delft email and I can release them in a beta state.

**Comment by Ecalpal** [comment]
> Please contact me on my tu delft email and I can release them in a beta state.

Thanks!

I have send an e-mail yesterday.
