### ISSUE TITLE
Radar Sensor Range

### ISSUE THREAD

**Issue by XiangyPeng** [tudelft-iv/view-of-delft-dataset#74]
Hi, I would like to ask about the maximum range of the objects obtained by radar in this dataset. Is it 50m? Is there any possibility to get the object and label with the range > 50m?
I checked the range by 'distance = np.linalg.norm((label['x'], label['y'], label['z'])),' it seems the maximum range is around 51m. Is it like so?
Is there any possibility of getting the object and label with the range > 50m or they are not being labeled?

Thank you in advance.

**Comment by andraspalffy** [comment]
Hello, as stated in the paper and on the website, the dataset is annotated up to 50 meters.
Radar was in short range mode, so you could see points up to 100 meters or so, but we do not have labels for those locations.

Andras
