### ISSUE TITLE
Lidar accumulation

### ISSUE THREAD

**Issue by qszgit** [tudelft-iv/view-of-delft-dataset#76]
Hello, I tried to use odomToCamera to accumulate lidar data, but the lidar I accumulated always has some errors. I would like to ask how you do millimeter wave accumulation?

**Comment by XiangyPeng** [comment]
Hi， we have the same problem. Have you solved it?

**Comment by AndrasPalffyPerciv** [comment]
Please state your challenge a bit more clear

**Comment by XiangyPeng** [comment]
> Please state your challenge a bit more clear

Hi， thank you for your reply!
For two continuous frames of radar point cloud. We transfer the point cloud into the camera coordinate, and the two-point clouds look correct; they have little distance. Then we transfer them into global coordinates by t_camera_map, the two point clouds become very far away from each other, as explained in issue102. 
Do you have any idea of it? Thank you in advance!
