### ISSUE TITLE
3d bounding box projection errors

### ISSUE THREAD

**Issue by UmangBDhanani** [tudelft-iv/view-of-delft-dataset#77]
When I am trying to project the 3d bounding boxes on the image, I am always getting a shift towards the sensor for every bounding box projection. As seen in the example images..

![Screenshot from 2023-10-26 18-00-00](https://github.com/tudelft-iv/view-of-delft-dataset/assets/84092636/2293596a-75b1-4b3a-8d9f-1b719b2299a7)
![Screenshot from 2023-10-26 18-00-41](https://github.com/tudelft-iv/view-of-delft-dataset/assets/84092636/6567ff03-cdc0-47c9-b32d-1ba5ed2687e2)

**Comment by andraspalffy** [comment]
[https://github.com/tudelft-iv/view-of-delft-dataset/blob/main/3_2d_visualization.ipynb](https://github.com/tudelft-iv/view-of-delft-dataset/blob/main/3_2d_visualization.ipynb
)
We have ready to use visualization tools. What you probably miss is the misalignement between lidar and camera z axis,

explained here
[https://tudelft-iv.github.io/view-of-delft-dataset/docs/ANNOTATION.html#kitti-formatted-labels](https://tudelft-iv.github.io/view-of-delft-dataset/docs/ANNOTATION.html#kitti-formatted-labels)

**Comment by UmangBDhanani** [comment]
Thank you @andraspalffy  for your reply. However I was mimicing the same visualization code into my own project but was missing a bit. Finally I have made it thanks.

**Comment by Petros626** [comment]
@UmangBDhanani can you tell how you solved it?
