### ISSUE TITLE
Issues related to dataset application

### ISSUE THREAD

**Issue by hehualin-tut** [tudelft-iv/view-of-delft-dataset#78]
Hello, first of all, thank you for your open source work. I would like to inquire about how long it will take to receive a response after submitting a dataset application during this time period, as I am not sure if the application has been approved. This is my student email address hhlin@stud.tjut.edu.cn Because I don't have a specific contact information, I raised this issue here, and I will close it in the future

best wishes!

**Comment by andraspalffy** [comment]
Should have got it right now. Sorry, I still do this manually to be GDPR compilant, so takes a while.
