### ISSUE TITLE
Did not get any reply after requiring the data

### ISSUE THREAD

**Issue by Ianpengg** [tudelft-iv/view-of-delft-dataset#79]
Hello, I have sent the request for the dataset a month ago but I haven't get any reply. Can you help me check with this ? Many thanks.
 #5

**Comment by andraspalffy** [comment]
Please send me  an email with the date, name, and email that you apply with. If you did not get it, probably you used an incorrect email (not educational or simply not working).

**Comment by ctc1111** [comment]
Did not get any reply after requiring the data
