### ISSUE TITLE
It was killed when creating the environment

### ISSUE THREAD

**Issue by novada0** [tudelft-iv/view-of-delft-dataset#80]
![image](https://github.com/tudelft-iv/view-of-delft-dataset/assets/107106546/98238950-9ac1-4bd4-8202-ee230c34c8c9)
I created the environment using environment.yml in a virtual machine, but it was killed like in the picture. What is the problem?

**Comment by andraspalffy** [comment]
This is a problem with your conda channels, not the sdk. Please try updating your conda.
