### ISSUE TITLE
About how to use the code? 

### ISSUE THREAD

**Issue by novada0** [tudelft-iv/view-of-delft-dataset#81]
Since I am new to this research area, I am not very familiar with the entire process. In the code repository view-of-delft-dataset you provided, it seems that specific tasks can only be accomplished on a particular dataset by calling functions inside the vod library. I would like to ask, if I generate my own millimeter-wave radar point cloud data, how should I use PointPillars for 3D object recognition? Can I still use the vod library to accomplish similar recognition tasks? I look forward to receiving your response. Thank you!

**Comment by andraspalffy** [comment]
Hello,
please understand that we do not have the resources to support custom research projects.

That being said, some guidellines:
1, vod devkit is for datamanagment and visualization only, there is no training or inference involved
2, for training and inference, we have used OpenPCDet as described in the paper
3, you can use both vod devkit and OpenPCdet with your data as long as you manage to convert it into a format they like - most probably KITTI format. See the example pcd files on our github page.

Best wishes, Andras
