### ISSUE TITLE
LiDAR Data Points not consistent

### ISSUE THREAD

**Issue by Michael-Schulze** [tudelft-iv/view-of-delft-dataset#87]
The LiDAR Data Points seems to be corrupted / wrong synchronized. In approx every 10 .. up to 30 frame the point cloud has "wholes" and it seems that some of the LiDAR points are using wrong height information.

You can see this behaviour e.g. in frame id 03285.

![Screenshot from 2024-03-18 09-44-27](https://github.com/tudelft-iv/view-of-delft-dataset/assets/28435324/2f907d5e-1ab4-46d1-946f-ffdb1533a0b8)

![Screenshot from 2024-03-18 09-35-05](https://github.com/tudelft-iv/view-of-delft-dataset/assets/28435324/5fbd7dc7-8f57-429f-9ee2-5d0c22263bb7)

![Screencast from 03-18-2024 09 41 39 AM](https://github.com/tudelft-iv/view-of-delft-dataset/assets/28435324/49d36543-907f-45ad-a782-487cb04d635d)

**Comment by andraspalffy** [comment]
That is interesting, did not really see that before. Do you see it at other frames too? It could be noisy sensor data, or some kind of float issue.

**Comment by Michael-Schulze** [comment]
It happens often, e.g. in frame ids:

03285
03306
03327
03342

So approx every 15 to 21 frame.

**Comment by andraspalffy** [comment]
Thanks for looking into this. After having a look at KITTI which has similar lidar, I think this is a sensor problem, with which we have to live with.
