### ISSUE TITLE
Hi, I have filed multiple requirements for access of the dataset. But I did not receive any reply.

### ISSUE THREAD

**Issue by zhanghaozhe23** [tudelft-iv/view-of-delft-dataset#92]
Thank you for your great work, I have filed the requirement for access of the dataset for a long time. But I did not receive any reply.
My email is zhanghaozhe23@shu.edu.cn

**Comment by andraspalffy** [comment]
I already sent it to this email, I sent it again now.

**Comment by zhanghaozhe23** [comment]
I am really sorry that I could not receive your email maybe because of the problem of the interception of my school's email. Could you please send it to my third-party email address? I am really interested in your work, thank you!

**Comment by zhanghaozhe23** [comment]
> I already sent it to this email, I sent it again now.

I am really sorry that I could not receive your email maybe because of the problem of the interception of my school's email. Could you please send it to my third-party email address? I am really interested in your work, thank you!

**Comment by andraspalffy** [comment]
We cannot send it to other email. Can you double check?
Write me an email at apalffy at tu delft nl
