### ISSUE TITLE
About Radar point cloud

### ISSUE THREAD

**Issue by EdenMoxe** [tudelft-iv/view-of-delft-dataset#93]
Hello! I tried to parse your Radar point cloud data and found that your RCS would be less than 0. How did you get such data? Or is it provided directly by the radar without your calculations? I only get constant greater than zero SNR data on my device, and I'm not quite sure how to convert to RCS data which can be less than 0.

**Comment by andraspalffy** [comment]
It is given in dBsm, which is very often negative.
