### ISSUE TITLE
A problem about creating point cloud

### ISSUE THREAD

**Issue by novada0** [tudelft-iv/view-of-delft-dataset#95]
Hello, may I ask how you generate the point cloud for millimeter-wave radar, especially the x, y, z coordinates? I assume it's based on the distance, azimuth angle, and elevation angle of the point cloud. I'm curious how you determine the elevation angle. Thank you!

**Comment by andraspalffy** [comment]
As explained in the paper, it is a 4D radar, thus it provides elevation on its own.
